# Site settings
title: Rol.io
description:
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Roli Khanna
user_description: Hello! I'm Roli, and I'm a Computer Science graduate student at Oregon State University. I started out as a Machine Learning, and now I'm stepping into the world of Human Computer Interaction.
user_title: I build intelligent and pretty things.
email: roli.khanna1995@gmail.com
twitter_username: RoliKhanna
github_username: RoliKhanna

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
